server:
  port: 8087
spring:
  application:
    name: walletExplorer
  profiles:
    active: test

#test
---
spring:
  profiles: test
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  #     cluster-name: elasticsearch_cluster

rocksdb:
  home: /Users/xinxinghu/Desktop/hduser/rocksdb/
  checkpoinHome: /Users/xinxinghu/Desktop/hduser/checkpoint


#dev
---
spring:
  profiles: dev
#  data:
#    elasticsearch:
#      cluster-nodes: 10.0.0.15:9300
#      cluster-name: elasticsearch_cluster
