server:
  port: 8082
spring:
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
info:
  app.name: zhq-microservicecloud
  company.name: www.zhq.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$